### PR TITLE
Add missing string header for memcpy

### LINKED ISSUE #106: `memcpy` not found -- missing `string.h`
When compiling `rocm_smi_lib` with GCC 12 errors like
```
/build/rocm-smi-lib/src/rocm_smi_lib-rocm-5.1.1/src/rocm_smi_gpu_metrics.cc:225:11: error: ‘memset’ was not declared in this scope
  225 |     (void)memset(data->temperature_hbm, 0,
      |           ^~~~~~
```
or
```
/build/rocm-smi-lib/src/rocm_smi_lib-rocm-5.1.1/src/rocm_smi_gpu_metrics.cc: In function ‘void map_gpu_metrics_1_2_to_rsmi_gpu_metrics_t(const rsmi_gpu_metrics_v_1_2*, rsmi_gpu_metrics_t*)’:
/build/rocm-smi-lib/src/rocm_smi_lib-rocm-5.1.1/src/rocm_smi_gpu_metrics.cc:242:5: error: ‘memcpy’ was not declared in this scope
  242 |     memcpy(rsmi_gpu_metrics, &gpu_metrics_v_1_2->base,
      |     ^~~~~~
```
appear. Adding `string.h` to the includes of this file fixes the isssue, see my PR.

### PR DESCRIPTION
**Pull request by tpkessler**
Fixes #106

### CODE REVIEW

**Review by keryell — APPROVED** [review]
Thanks.

**Comment by tpkessler** [comment]
Can we get this merged? The issue is still present in ROCm 5.4.,0.

**Comment by tpkessler** [comment]
Any progress? @zhang2amd @kentrussell

**Comment by dmitrii-galantsev** [comment]
Fixed in https://github.com/RadeonOpenCompute/rocm_smi_lib/commit/99034af009ab141163c83a817d6ac8380370760d

**Pull request closed without merging**
